### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by jobrienr** [june5471/Vowel#1]
Attached is my peer review! @datalorax

[O'Brien_PeerReview.docx](https://github.com/june5471/Vowel/files/2603728/O.Brien_PeerReview.docx)

**Comment by datalorax** [comment]
Thanks Jackie!

Ideally, it would be have been great to have your review transposed here, using markdown syntax, rather than having to open an external word doc (not a bit deal, but makes it a bit more convenient).

Really nice feedback on the inline code part.

You state

> Instead of having the group name repeat down all the rows, it could be nice if you could have the group name only listed once for each group, with some delineation indicating that the first 9 rows are NNS, and the second 9 rows are NS

I'm not positive I follow here but it sounds like this could be a great spot for `spread`

One other thing I notice when looking at your repository - you shouldn't ever really need to have `_v2`, `_v3`, etc., because git is tracking the entire history of a file. So you should always be able to go back to a specific version if you wanted to.

Your `sep = "(?<=[A-Za-z])(?=[0-9])")` is cool... do you know what it means? It's a fairly complex regular expression. Generally I would try to avoid using code you don't understand. If you understand it, great! But in this case, I think it's actually easier to just use `sep = -1`, unless there's some reason that's not working for you.

I like the feedback on what might be good to hear more about during the presentation.

Really great feedback!
